apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: petinsurance
spec:
  revisionHistoryLimit: 1
  replicas: 1
  template:
    metadata:
      labels:
        app: petinsurance
    spec:
      containers:
      - name: petinsurance
        image: gcr.io/projectthreeie/petinsurance:v1.0
        env:
        - name: PetInsurancePassword
          valueFrom:
            secretKeyRef:
              name: jdbc-password
              key: key
        - name: PetInsuranceURL
          value: "jdbc:postgresql://34.70.42.108:5432/postgres"
        - name: PetInsuranceUsername
          value: "postgres"
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /RevaturePetInsurance-0.0.1-SNAPSHOT/log/health.app
            port: 8080
        resources:
          limits:
            cpu: 70m
          requests:
            cpu: 70m

---
apiVersion: v1
kind: Service
metadata:
  name: petinsurance
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: petinsurance