apiVersion: "v1"
kind: "Service"
metadata:
  # annotations:
  #   kubectl.kubernetes.io/last-applied-configuration: |
  #     {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"supportforceapp":"tomcat-backend"},"name":"tomcat-backend-service","namespace":"default"},"spec":{"ports":[{"port":80,"protocol":"TCP","targetPort":8080}],"selector":{"supportforceapp":"tomcat-backend"},"type":"ClusterIP"}}
  # creationTimestamp: "2019-09-24T04:05:40Z"
  labels:
    supportforceapp: "tomcat-backend-service"
  name: "tomcat-backend-service"
  namespace: "backend"
  # resourceVersion: "1803"
  # selfLink: /api/v1/namespaces/default/services/tomcat-backend-service
  # uid: 92b3e3ff-de80-11e9-8dd4-42010a9600d1
spec:
  clusterIP: 10.89.13.105
  loadBalancerIP: 35.221.50.112
  loadBalancerSourceRanges:
    - "0.0.0.0/0"
  ports:
  - port: 80
    protocol: "TCP"
    targetPort: 8080
  selector:
    app: "tomcat-backend"
  sessionAffinity: "None"
  type: "LoadBalancer"
# status:
#   loadBalancer: {}
