runtime: custom
env: flex
#service:  safenurturebackend
service:  backend
# this named default now to make an error go away
resources:
 cpu: 1
 memory_gb: 1
automatic_scaling:
 min_num_instances: 1
 max_num_instances: 2
 cool_down_period_sec: 200
 cpu_utilization:
   target_utilization: 0.7