version: 2.1
orbs:
  gcp-gke: circleci/gcp-gke@0.1.0
jobs:
  buildfrontend: ## build the angular artifacts from ng build
    description: build angular artifacts and push to storage bucket
    machine: true
    steps:
      - checkout
      ## replace build environment vars file
      - run: cp .circleci/staging.environment.ts SupportForce/src/environments/environment.ts
      - run: cp .circleci/staging.environment.prod.ts SupportForce/src/environments/environment.prod.ts
      ## authorize with gcp service account key
      - run: cat .circleci/support-force-circleci.json | docker login -u _json_key --password-stdin https://gcr.io
      ## build the application image
      - run: docker build -f SupportForce/stagingfe.dockerfile -t gcr.io/support-force/supportforce:latest .
      ## push the image to container registry
      - run: docker push gcr.io/support-force/supportforce:latest
      ## run container
      - run: docker run gcr.io/support-force/supportforce:latest
workflows:
  buildfrontend:
    jobs:
      - buildfrontend
